---
title: ''
editor:
  render-on-save: true
format:
  pdf:
    documentclass: exam
    papersize: letter
    fontsize: 9pt
    include-in-header:
      - ./my-header.tex
      - ./my-macros.tex
    toc: false
    number-sections: true
    colorlinks: false
---

\noindent\makebox[0.75\textwidth]{Name:\enspace\hrulefill}

\vspace{5mm}

\begin{center}
    \LARGE{\textbf{In-class final, EC421}}
    \\ \large{180 points possible}
\end{center}

\vspace{5mm}

```{r, setup, include=FALSE}
# Packages
library(pacman)
p_load(fastverse, extrafont, latex2exp, ggplot2, scales)
```

## True or false (105 points; 35 questions)

\textbf{Note:} In this section, select the correct answer (true or false). You do not need to explain your answer.

\begin{questions}

\tf{T} If the disturbance in an OLS regression correlates with a regressor, exogeneity is violated.

\tf{F} Homoskedasticity means that the variance of the disturbances differs across observations.

\tf{F} In the potential outcomes framework, $\mathbb{E}[\text{Y}_{1} | D_{i}=0]$ represents the average untreated outcome for the treated group.

\tf{T} The \textit{fundamental problem of causal inference} is that we cannot observe the both the treated and untreated outcomes for the same individual.

\tf{F} The variable $x_t = 0.3 t + \varepsilon_{t}$ is stationary (assume $\varepsilon_{t}$ is mean zero).

\tf{F} \textit{Selection bias} occurs when the individuals \textit{select} into treatment or control groups.

\tf{T} Measurement error in an explanatory variable tends to bias OLS's coefficient estimates toward zero.

\tf{T} There are situations where OLS is consistent but biased for estimating coefficients.

\tf{F} The instrumental variable (IV) estimator requires that the regressor of interest is exogenous.

\tf{F} The variance of the disturbance affects whether OLS is biased for estimating coefficients.

\tf{T} Adding additional variables always increases R$^2$.

\tf{F} The Goldfeld-Quandt test is a test for autocorrelation.

\tf{T} OLS is biased when estimating coefficients in models with lagged outcome variables.

\tf{T} The presence of omitted-variable bias implies that OLS is also inconsistent.

\tf{T} If the disturbance is heteroskedastic, conventional OLS-based confidence intervals will be invalid.

\tf{F} The first stage of two-stage least squares (2SLS) involves regressing the outcome variable on the instrumental variable.

\tf{T} Two-stage least squres can address bias arising from omitted variables.

\tf{F} If OLS is biased for estimating $\beta_2$ below, then it is also inconsistent for estimating $\beta_2$.
$$
  \text{Health}_t = \beta_0 + \beta_1 \text{Income}_t + \beta_2 \text{Health}_{t-1} + u_t
$$

\tf{F} With a \textit{p}-value of 0.997, you would strongly reject the null hypothesis.

\tf{F} Random walks are non-stationary because their means grow over time.

\tf{T} In the Rubin causal model, $\text{Y}_{1i}$ refers to the outcome for individual $i$ when they receive treatment.

\tf{F} If $u_i$ correlates with $u_j$, then exogeneity is violated.

\tf{T} The OLS estimator estimates the coefficients by minimizing $\sum_i (y_i \hat{y}_i)^2$, where $\hat{y}_i = \hat{\beta}_0 + \hat{\beta}_1 x_i$ (for a simple linear regression).

\tf{T} Consistency describes the behavior of an estimator as the sample size grows.

\tf{F} If a Goldfeld-Quandt test finds $\text{SSE}_1 / \text{SSE}_2 > 100$, then it will likely conclude that there is no statistically significant evidence of heteroskedasticity.

\tf{F} In the model $\text{Births}_t = \beta_0 + \beta_1 \text{Income}_t + u_t$, the parameter $\beta_1$ gives the effect of income in the previous time period on births in the current period.

\tf{T} \textit{Cluster-robust} standard errors account for the possibility that $u_i$ may correlate with $u_j$ for some individuals.

\tf{T} Residuals are observable; disturbances are not.

\tf{T} The econometric model below allows the effect of age on health to depend upon the individual's gender.
\begin{equation*}
  \text{Health}_i = \beta_0 + \beta_1 \text{Female}_i + \beta_2 \text{Age}_i + \beta_3 \text{Female}_i \times \text{Age}_i + u_i
\end{equation*}

\tf{T} In the econometric model below, the effect of age can depend on the individual's age.
\begin{equation*}
  \text{Health}_i = \beta_0 + \beta_1 \text{Age}_i + \beta_2 \text{Age}_i^2 + u_i
\end{equation*}

\tf{F} Correlated disturbances make OLS biased when estimating coefficients.

\tf{T} Randomizing the explanatory variable helps avoid selection bias.

\tf{T} In the model below, if the disturbance is \textit{not} autocorrelated, then OLS consistently estimates the coefficients (assume the `standard' assumptions hold).
$$y_{t} = \beta_0 + \beta_1 x_{t} + \beta_2 x_{t-1} + \beta_3 y_{t-1} + u_t$$

\tf{F} In the model
$$\log \text{Quantity}_t = \beta_0 + \beta_1 \log \text{Price}_t + u_t$$
if $\hat{\beta}_1 = -0.3$, then, on average, a one-percent increase in price generates a 30-percent reduction in quantity (all else equal).

\tf{T} If the variable $x_t$ is a random walk, then $\Delta x_t = x_t - x_{t-1}$ is stationary.

\tf{T} The definition of causality discussed in our class assumes that the treatment effect for and individual does not depend upon the treatment status of other individuals.

\end{questions}

## Short answer (75 points; 16 questions)

\textbf{Note:} In this section, briefly answer the questions/prompts in 1--3 short (and complete) sentences. We will deduct points for excessively long answers.

\begin{questions}

\setcounter{question}{35}

\question{} Suppose you estimate the following model with OLS
\begin{equation*}
  \text{Income}_i = \beta_0 + \beta_1 \text{Education}_i + \beta_2 \text{Female}_i + \beta_3 \text{Education}_i \times \text{Female}_i + u_i
\end{equation*}
and find parameter estimates $\hat{\beta}_0 = 30$, $\hat{\beta}_1 = 1$, $\hat{\beta}_2 = -5$, and $\hat{\beta}_3 = 0.5$.

\begin{parts}
  \part{(5 points)} Interpret $\hat{\beta}_3$ in the context of the model. \vspace{\stretch{1}}
  \part{(5 points)} What is the expected income for a non-female individual with 12 years of education? \vspace{\stretch{1}}
  \part{(5 points)} Explain how the regression above estimates two lines---and provide the slope of each line.  \vspace{\stretch{1}}
  \part{(5 points)} Explain how you could use this model to test for gender-based discrimination.  \vspace{\stretch{1}}
\end{parts}

\newpage

\question{} People commonly debate the impact of the minimum wage on unemployment. Suppose you have data on unemployment and minimum wage for 100 cities in the United States.

\begin{parts}
  \part{(3 points)} Write down the econometric (regression) model you would use to estimate the effect of minimum wage on unemployment. \vspace{\stretch{.8}}
  \part{(2 points)} Which parameter in your model gives the effect of minimum wage on unemployment? \vspace{\stretch{.8}}
  \part{(5 points)} Suppose you estimate your model (in (a) above) with OLS. Will these OLS estimates provide causal evidence about the effect of minimum wage on unemployment? Explain your answer. \vspace{\stretch{1}}
  \part{(5 points)} Could instrumental variables help here? Explain. \vspace{\stretch{1}}
\end{parts}

\newpage

\short Define the concept of a \textit{standard error}.

\vspace{\stretch{1}}

\short Using mathematical notation, explain the concept of \textit{exogeneity}. Then explain why exogeneity is important for OLS.

\vspace{\stretch{1}}

\short Suppose you are analyzing time-series data for your job. Why should you be concerned about non-stationarity?

\vspace{\stretch{1}}

\newpage

\short The probability limit of the instrumental variables (IV) estimator (with instrument $z$, endogenous regressor $x$, and disturbance $u$) is
$$
  \text{plim} \; \hat{\beta}_{\text{IV}} = \beta + \dfrac{\text{Cov}(z, u)}{\text{Cov}(z, x)}
$$
Use the equation above to explain how a valid instrument makes the IV estimator consistent.

\vspace{\stretch{1}}

\short Explain how correlated disturbances can affect OLS.

\vspace{\stretch{1}}

\short Explain how randomized experiments avoid omitted-variable bias.

\vspace{\stretch{1}}

\newpage

\short Suppose you want to know how a recent advertising campaign affected sales. You have monthly data on sales (in dollars) and advertising spending (in dollars) for several years. Write down the econometric model you would use to estimate the effect of advertising on sales.

\vspace{\stretch{1}}

\short What are the key assumptions required to interpret your coefficient estimates from the model in the previous question as causal? Are these assumptions plausible in this context? Explain.

\vspace{\stretch{1}}


\end{questions}
